from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor
from services.session_store import session_store
from services.priority_alert_service import PriorityAlertService
import os


class ReportService:

    def generate_pdf(self):
        data_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'data')
        file_path = os.path.join(data_dir, 'Genomic_Report.pdf')
        os.makedirs(data_dir, exist_ok=True)

        c = canvas.Canvas(file_path, pagesize=A4)
        width, height = A4

        # ---------- THEME COLORS ----------
        BG = HexColor("#020617")
        CARD = HexColor("#0f172a")
        BORDER = HexColor("#38bdf8")
        TEXT = HexColor("#e5e7eb")
        MUTED = HexColor("#9ca3af")

        RED = HexColor("#ef4444")     # High
        YELLOW = HexColor("#facc15")  # Medium
        GREEN = HexColor("#22c55e")   # Low

        margin = 36
        content_top = height - 120
        y = content_top

        # ---------- PAGE FRAME ----------
        def draw_page_frame():
            nonlocal y
            c.setFillColor(BG)
            c.rect(0, 0, width, height, stroke=0, fill=1)

            c.setFillColor(CARD)
            c.setStrokeColor(BORDER)
            c.setLineWidth(2)
            c.roundRect(
                margin, margin,
                width - margin * 2,
                height - margin * 2,
                18,
                stroke=1,
                fill=1
            )

            # Header
            c.setFillColor(BORDER)
            c.setFont("Helvetica-Bold", 18)
            c.drawString(margin + 24, height - 70, "Genomics Detector")

            c.setFont("Helvetica", 12)
            c.setFillColor(MUTED)
            c.drawString(
                margin + 24,
                height - 92,
                "Final Genomic Analysis Report"
            )

            y = content_top

        # ---------- START PAGE ----------
        draw_page_frame()

        # ---------- DETECTED DISEASES ----------
        c.setFillColor(TEXT)
        c.setFont("Helvetica-Bold", 14)
        c.drawString(margin + 24, y, "Detected Diseases")
        y -= 20

        c.setFont("Helvetica", 11)

        for d in session_store.disease_results:
            if y < 90:
                c.showPage()
                draw_page_frame()

            c.drawString(
                margin + 40,
                y,
                f"🧬 {d['disease']} — Source: {d['source']}"
            )
            y -= 14

        y -= 26

        # ---------- PRIORITY ALERTS ----------
        c.setFont("Helvetica-Bold", 14)
        c.setFillColor(TEXT)
        c.drawString(
            margin + 24,
            y,
            "Priority Alerts (High / Medium / Low)"
        )
        y -= 20

        priority_data = PriorityAlertService().generate_alerts()

        PRIORITY_ORDER = [
            ("high", "High Priority", RED),
            ("medium", "Medium Priority", YELLOW),
            ("low", "Low Priority", GREEN)
        ]

        for level, label, color in PRIORITY_ORDER:
            diseases = priority_data.get(level, [])

            if y < 110:
                c.showPage()
                draw_page_frame()

            c.setFont("Helvetica-Bold", 12)
            c.setFillColor(color)
            c.drawString(margin + 40, y, label)
            y -= 14

            c.setFont("Helvetica", 11)
            c.setFillColor(TEXT)

            if diseases:
                for disease in diseases:
                    if y < 90:
                        c.showPage()
                        draw_page_frame()
                    c.drawString(
                        margin + 60,
                        y,
                        f"🧬 {disease}"
                    )
                    y -= 12
            else:
                c.setFillColor(MUTED)
                c.drawString(margin + 60, y, "None")
                y -= 12

            y -= 10

        # ---------- FOOTER ----------
        c.setFillColor(MUTED)
        c.setFont("Helvetica", 9)
        c.drawCentredString(
            width / 2,
            28,
            "Generated by Genomics Detector"
        )

        c.save()
        return file_path
